nats:
  host: localhost
  port: 4222
  healthcheck_file: /tmp/nats_worker_healthbeat
  loop_sleep_duration: 2
  connect_name: transactions
  reconnect_time_wait: 5
  connect_timeout: 5
  ping_interval: 120
  max_outstanding_pings: 3

publishers:
  project:
    stream_name: projects_service
    main_subject_name: project
    creation_subject_name: created
    update_subject_name: updated
    deletion_subject_name: deleted
    restoration_subject_name: restored
  section:
    stream_name: projects_service
    main_subject_name: section
    creation_subject_name: created
    update_subject_name: updated
    deletion_subject_name: deleted
    restoration_subject_name: restored
  discipline:
    stream_name: projects_service
    main_subject_name: discipline
    creation_subject_name: created
    update_subject_name: updated
    deletion_subject_name: deleted
    restoration_subject_name: restored
  stage:
    stream_name: projects_service
    main_subject_name: stage
    creation_subject_name: created
    update_subject_name: updated
    deletion_subject_name: deleted
    restoration_subject_name: restored
  part:
    stream_name: projects_service
    main_subject_name: part
    creation_subject_name: created
    update_subject_name: updated
    deletion_subject_name: deleted
    restoration_subject_name: restored

db:
  host: localhost
  port: 5432
  user: companies_service
  database: companies_service
  password_file: /tmp/transactions/db_password
  pool:
    min_size: 10
    max_size: 20
    max_inactive_connection_lifetime: 300
    max_connection_lifetime: 3600
    timeout: 20
