logging:
  level: info

nats:
  host: localhost
  port: 4222
  healthcheck_file: /tmp/nats_worker_healthbeat
  loop_sleep_duration: 2
  connect_name: transactions
  reconnect_time_wait: 5
  connect_timeout: 5
  ping_interval: 120
  max_outstanding_pings: 3
  email:
    stream_name: email
    send_subject_name: send

db:
  host: localhost
  port: 5432
  user: users
  database: users
  password_file: /tmp/transactions/db_password
  pool:
    min_size: 10
    max_size: 20
    max_inactive_connection_lifetime: 300
    max_connection_lifetime: 3600
    timeout: 20
